spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ielp
    username: root
    password: SqlADC015@


    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        resetEnable: false
#        login-username: admin
#        login-password: admin666
      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      aop-patterns: com.company.ielp.app.*
  servlet:
    multipart:
      max-file-size: 10MB
